package com.scheduling.scheduler;

/**
The request body to create employee shouldn't contain id
 as it will be auto-generated by database.
 YOU CAN'T SET IT BY YOURSELF remember as there is no setter for id in it's Entity class.
*/

/**
 * @param name
 * @param email
 * @param role
 */
public record CreateEmployeeRequest(String name, String email, String role) {
}